### PR TITLE
Fix project compliance

### LINKED ISSUE #170: 6.2 project compliance
As noted: https://github.com/BHoM/RFEM5_Toolkit/pull/169/checks?check_run_id=14442155682

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #170

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 14745051792

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by desaiwangBH — APPROVED** [review]
Check for project-compliance has passed, so I'm approving after talking with Fraser.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
