### PR TITLE
Update RFEM5 Engine to fix Versioning issues.

### LINKED ISSUE #167: Migrate Convert methods to Adapter
Some Engine Convert methods are causing versioning failures. They should sit within the adapter project anyway. Move them up and resolve versioning.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #167

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 13982440220

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by CKBoulter — APPROVED** [review]
Checks are passing as explained by @FraserGreenroyd , changes meet the needs he's outlining for the DevOps issue being resolved.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
